/**
 * Forms, subforms, detail/print pages, Studio tabs, and extra reports that
 * are not sidebar NAV list routes. Merged into CATALOG by workflowCatalog.ts.
 */
import type { CatalogEntry, CatalogKind, DemoTenantKey } from "./workflowCatalog"

const ALL: DemoTenantKey[] = [
  "simple", "services", "trader", "manufacturing", "telecom", "pra", "hospital", "spinning", "processing",
]
const MILL: DemoTenantKey[] = ["manufacturing", "spinning", "processing"]
const WB: DemoTenantKey[] = ["manufacturing", "spinning"]

type Row = {
  id: string
  kind: CatalogKind
  title: string
  href: string
  explanation: string
  segment: string
  captureTenant: DemoTenantKey
  tags: string[]
  modules?: string[]
  tenants?: DemoTenantKey[]
  capturePath?: string
  captureIdFrom?: string
  captureIdFrom2?: string
  captureIdField?: string
  steps?: string[]
  gl?: string
}

function row(r: Row): CatalogEntry {
  const modules = r.modules ?? ["base"]
  return {
    ...r,
    modules,
    tenants: r.tenants ?? (modules.includes("base") ? ALL : r.tenants ?? ALL),
  }
}

function studio(tab: "fields" | "forms" | "print", entity: string, title: string, explanation: string): CatalogEntry {
  const path = `/settings/studio?tab=${tab}&entity=${entity}`
  return row({
    id: `subform-studio-${tab}-${entity}`,
    kind: "subform",
    title,
    href: path,
    capturePath: path,
    captureTenant: "services",
    segment: "System",
    tags: ["settings", "studio", "workflow"],
    explanation,
    steps: [
      "Open Settings → Studio (admin/owner).",
      `Pick the ${tab === "print" ? "Print" : tab === "forms" ? "Form layout" : "Fields"} tab and the ${entity} entity.`,
      "Save — custom keys never post to the GL; they print and export only.",
    ],
  })
}

const STUDIO: CatalogEntry[] = [
  studio("fields", "invoice", "Studio · Fields · Invoice",
    "Custom columns on sales invoices (x.* keys). Weighbridge install stamps x.gate_pass_no and optional x.lot_ref. Cap per entity; archived keys stay on historical docs."),
  studio("fields", "bill", "Studio · Fields · Bill",
    "Custom columns on vendor bills. Same catalog/cap as invoices — used for GRN references, vehicle, or mill lot numbers that should not hit the GL."),
  studio("fields", "customer", "Studio · Fields · Customer",
    "Extra customer master fields (NTN already exists as a core column). Studio fields show on the customer form and optionally on invoice print."),
  studio("fields", "product", "Studio · Fields · Product",
    "Extra product attributes (HS/PCT are core). Custom keys can show on the invoice line picker and print template."),
  studio("fields", "vendor", "Studio · Fields · Vendor",
    "Extra vendor master fields (WHT flags are core). Use Studio for mill contractor codes or Peppol endpoint ids that are not GL accounts."),
  studio("forms", "invoice", "Studio · Form layout · Invoice",
    "Show/hide and require core + custom fields on the invoice form. Locked keys (customer, dates, lines) cannot be removed — they are the posting contract."),
  studio("forms", "bill", "Studio · Form layout · Bill",
    "Bill form schema: hide unused fields, mark custom keys required. Locked vendor/date/line keys stay so AP posting cannot be bypassed."),
  studio("forms", "customer", "Studio · Form layout · Customer",
    "Customer form layout. Name stays locked. Hide address or tax ids you do not use; required custom keys block save until filled."),
  studio("forms", "product", "Studio · Form layout · Product",
    "Product form layout. Type and name stay locked. Toggle deferred-revenue months or custom mill specs onto the create/edit form."),
  studio("forms", "vendor", "Studio · Form layout · Vendor",
    "Vendor form layout. Name stays locked. Surface WHT and Studio keys for AP clerks without exposing unused tax fields."),
  studio("print", "invoice", "Studio · Print · Invoice",
    "HTML print templates for invoices. Built-in default can be copied; tokens include custom x.* fields. Landscape/portrait is template CSS, not PrintHeader."),
  studio("print", "bill", "Studio · Print · Bill",
    "HTML print templates for vendor bills. Copy the built-in, add custom fields, set as default. Historical bills keep the template they were printed with."),
]

const FORMS: CatalogEntry[] = [
  row({ id: "form-customer-new", kind: "form", title: "New customer", href: "/customers/new",
    captureTenant: "services", segment: "Sales", tags: ["sales", "workflow"],
    explanation: "Customer master create. NTN/CNIC/GSTIN print on invoices. Opening balance is memo until you post a JV. Studio fields follow the customer form schema." }),
  row({ id: "form-vendor-new", kind: "form", title: "New vendor", href: "/vendors/new",
    captureTenant: "services", segment: "Purchases", tags: ["purchases", "workflow"],
    explanation: "Vendor master create. WHT flags drive BillPayment.wht_amount. Opening AP is memo until a JV. Studio fields follow the vendor form schema." }),
  row({ id: "form-product-new", kind: "form", title: "New product", href: "/products/new",
    captureTenant: "trader", segment: "Inventory", tags: ["inventory", "sales", "workflow"],
    explanation: "Product create: stock vs service, unit, tax, deferred flag + recognition months, SSP for IFRS 15, category. Stock products participate in COGS on invoice." }),
  row({ id: "form-employee-new", kind: "form", title: "New employee", href: "/employees/new",
    captureTenant: "hospital", segment: "Payroll", modules: ["hrm"], tenants: ["hospital"], tags: ["payroll", "workflow"],
    explanation: "Employee master (EMP-seq). CNIC/bank for payslips. Salary structure is a separate tab after save — components come from the catalog." }),
  row({ id: "form-payment-received-new", kind: "form", title: "New payment received", href: "/payments-received/new",
    captureTenant: "services", segment: "Sales", tags: ["sales", "banking", "gl", "workflow"],
    explanation: "AR receipt form. Pick customer, bank/cash account, allocate to open invoices. Excess can sit as an advance. Posts Dr bank / Cr AR.",
    gl: "Dr 1010 Bank (or cash) / Cr 1100 AR. Unapplied remainder may credit advances." }),
  row({ id: "form-bill-payment-new", kind: "form", title: "New bill payment", href: "/bill-payments/new",
    captureTenant: "services", segment: "Purchases", tags: ["purchases", "banking", "gl", "workflow"],
    explanation: "AP payment form. Allocate to open bills; WHT amount is stored when the vendor is flagged. Posts Dr AP / Cr bank.",
    gl: "Dr 2000 AP / Cr 1010 Bank. WHT is a separate payable when configured." }),
  row({ id: "form-bank-import-new", kind: "form", title: "New bank import", href: "/bank-imports/new",
    captureTenant: "services", segment: "Banking", tags: ["banking", "workflow"],
    explanation: "Upload CSV/OFX statement lines. Lines are facts from the bank — they never auto-post. Match them on the import detail, then close a reconciliation." }),
  row({ id: "form-payroll-new", kind: "form", title: "New payroll run", href: "/payroll/new",
    captureTenant: "hospital", segment: "Payroll", modules: ["hrm"], tenants: ["hospital"], tags: ["payroll", "gl", "workflow"],
    explanation: "Draft a payroll run from employee salary structures for a pay period. Attendance can drive LOP. Approve then post GL (PR-YYYY-seq).",
    gl: "On post: Dr Salary Expense / Cr Salaries Payable." }),
  row({ id: "form-transfer-new", kind: "form", title: "New warehouse transfer", href: "/inventory/transfers/new",
    captureTenant: "trader", segment: "Inventory", modules: ["inventory"], tenants: ["trader", "manufacturing", "hospital", "telecom", "spinning", "processing"],
    tags: ["inventory", "workflow"],
    explanation: "Stock transfer between locations (ship then receive). In-transit qty sits at the destination after ship until receive. consume_stock itself is not location-scoped." }),
  row({ id: "form-bom-new", kind: "form", title: "New bill of materials", href: "/manufacturing/boms/new",
    captureTenant: "manufacturing", segment: "Manufacturing", modules: ["production"], tenants: ["manufacturing"], tags: ["manufacturing", "inventory"],
    explanation: "BoM header + component lines + finished item. Used by production orders to issue RM and receipt FG." }),
  row({ id: "form-grn-new", kind: "form", title: "New goods receipt", href: "/manufacturing/grn/new",
    captureTenant: "manufacturing", segment: "Manufacturing", modules: ["production"], tenants: ["manufacturing"], tags: ["purchases", "inventory", "gl"],
    explanation: "GRN against a PO when you are not using gate inward. Receipts stock and can feed the bill. Print template is portrait voucher-style." }),
  row({ id: "form-mo-new", kind: "form", title: "New production order", href: "/manufacturing/production-orders/new",
    captureTenant: "manufacturing", segment: "Manufacturing", modules: ["production"], tenants: ["manufacturing"], tags: ["manufacturing", "gl", "workflow"],
    explanation: "Work order: pick BoM, qty, location. Issue components (Dr WIP / Cr RM), complete output (Dr FG / Cr WIP), optional scrap reason." }),
  row({ id: "form-po-new", kind: "form", title: "New purchase order", href: "/manufacturing/purchase-orders/new",
    captureTenant: "manufacturing", segment: "Purchases", modules: ["purchase_store"], tenants: MILL, tags: ["purchases", "workflow"],
    explanation: "PO form. With purchase_store and require_purchase_chain, a bare PO is rejected unless it carries an approved comparative_id." }),
  row({ id: "form-gi-new", kind: "form", title: "New gate inward", href: "/purchases/gate-inward/new",
    captureTenant: "manufacturing", segment: "Purchases", modules: ["purchase_store"], tenants: MILL, tags: ["purchases", "inventory"],
    explanation: "Vehicle/challan vs remaining PO qty. Price-free PO picker so a gate-only user never sees rates. Memo — no GL until the bill." }),
  row({ id: "form-go-new", kind: "form", title: "New gate outward", href: "/store/gate-outward/new",
    captureTenant: "manufacturing", segment: "Store", modules: ["purchase_store"], tenants: MILL, tags: ["inventory", "sales"],
    explanation: "Dispatch exit. Invoice/debit-note sources approve on create; scrap is draft until approve (then consume_stock posts GL)." }),
  row({ id: "form-si-new", kind: "form", title: "New store issue", href: "/store/issues/new",
    captureTenant: "manufacturing", segment: "Store", modules: ["purchase_store"], tenants: MILL, tags: ["inventory", "gl", "workflow"],
    explanation: "Departmental consumption. Pick an Expense-type debit account (analytic-tagged) and lines — save posts GL + relieves stock immediately.",
    gl: "Dr 5xxx Expense / Cr 1200 Inventory on create." }),
  row({ id: "form-tp-lot-new", kind: "form", title: "New processing lot", href: "/processing/lots/new",
    captureTenant: "processing", segment: "Processing", modules: ["textile_processing"], tenants: ["processing"], tags: ["processing", "inventory"],
    explanation: "Grey inward lot against a sales order. Customer-owned grey is custody stock until processed, packed, and dispatched." }),
  row({ id: "form-wv-contract-new", kind: "form", title: "New weaving contract", href: "/weaving/contracts/new",
    captureTenant: "manufacturing", segment: "Weaving", modules: ["weaving"], tenants: ["manufacturing"], tags: ["weaving", "manufacturing"],
    explanation: "Weaving contract with embedded quality, construction, and rates. Memo/ops in v1 — no GL. Yarn inward and production hang off this record." }),
  row({ id: "form-demand-quote-new", kind: "form", title: "New vendor quotation", href: "/purchases/demands",
    capturePath: "/purchases/demands/{id}/quotations/new", captureIdFrom: "/api/purchase-demands",
    captureTenant: "manufacturing", segment: "Purchases", modules: ["purchase_store"], tenants: MILL,
    tags: ["purchases", "workflow"],
    explanation: "Enter rates against each demand line for one vendor. Writes freeze once the demand’s comparative is approved or converted. Self-contained on the demand — no separate quotation list." }),
]

const DETAILS: CatalogEntry[] = [
  row({ id: "form-invoice-detail", kind: "form", title: "Invoice detail", href: "/invoices",
    capturePath: "/invoices/{id}", captureIdFrom: "/api/invoices",
    captureTenant: "services", segment: "Sales", tags: ["sales", "gl"],
    explanation: "Posted invoice with lines, tax, allocations, Studio fields, and GL voucher link. Edit is blocked after recognition on deferred lines." }),
  row({ id: "form-invoice-edit", kind: "form", title: "Edit invoice", href: "/invoices",
    capturePath: "/invoices/{id}/edit", captureIdFrom: "/api/invoices",
    captureTenant: "services", segment: "Sales", tags: ["sales", "gl"],
    explanation: "Invoice edit rebuilds deferred schedules if nothing is recognised yet. Allocated receipts block destructive edits. Dr must still equal Cr." }),
  row({ id: "form-invoice-print", kind: "form", title: "Invoice print", href: "/invoices",
    capturePath: "/invoices/{id}/print", captureIdFrom: "/api/invoices",
    captureTenant: "services", segment: "Sales", tags: ["sales", "studio"],
    explanation: "Printable invoice using the Studio print template (or built-in). Dates fmtDate dd-mm-yy; IAS 1.49 company block from Settings." }),
  row({ id: "form-invoice-receipt", kind: "form", title: "Invoice receipt slip", href: "/invoices",
    capturePath: "/invoices/{id}/receipt", captureIdFrom: "/api/invoices",
    captureTenant: "services", segment: "Sales", tags: ["sales"],
    explanation: "Thermal-style receipt companion to the full invoice print — used at the counter when POS is not installed." }),
  row({ id: "form-bill-detail", kind: "form", title: "Bill detail", href: "/bills",
    capturePath: "/bills/{id}", captureIdFrom: "/api/bills",
    captureTenant: "trader", segment: "Purchases", tags: ["purchases", "gl"],
    explanation: "Posted vendor bill with stock/expense lines, WHT, and the AP voucher. Linked GI/PO show when purchase_store is on." }),
  row({ id: "form-bill-edit", kind: "form", title: "Edit bill", href: "/bills",
    capturePath: "/bills/{id}/edit", captureIdFrom: "/api/bills",
    captureTenant: "trader", segment: "Purchases", tags: ["purchases", "gl"],
    explanation: "Bill edit before payment allocation. Stock qty adjustments reverse and re-receive inventory layers." }),
  row({ id: "form-bill-print", kind: "form", title: "Bill print", href: "/bills",
    capturePath: "/bills/{id}/print", captureIdFrom: "/api/bills",
    captureTenant: "trader", segment: "Purchases", tags: ["purchases", "studio"],
    explanation: "Printable vendor bill from the Studio bill template." }),
  row({ id: "form-cn-detail", kind: "form", title: "Credit note detail", href: "/credit-notes",
    capturePath: "/credit-notes/{id}", captureIdFrom: "/api/credit-notes",
    captureTenant: "services", segment: "Sales", tags: ["sales", "gl"],
    explanation: "Sales return allocated against the original invoice. Reverses revenue/tax/stock as needed without deleting history." }),
  row({ id: "form-cn-print", kind: "form", title: "Credit note print", href: "/credit-notes",
    capturePath: "/credit-notes/{id}/print", captureIdFrom: "/api/credit-notes",
    captureTenant: "services", segment: "Sales", tags: ["sales"],
    explanation: "Printable credit note (portrait). Number prefix encodes the type — no extra voucher badge." }),
  row({ id: "form-dn-detail", kind: "form", title: "Debit note detail", href: "/debit-notes",
    capturePath: "/debit-notes/{id}", captureIdFrom: "/api/debit-notes",
    captureTenant: "trader", segment: "Purchases", tags: ["purchases", "gl"],
    explanation: "Purchase return reversing AP and stock/expense from the original bill." }),
  row({ id: "form-dn-print", kind: "form", title: "Debit note print", href: "/debit-notes",
    capturePath: "/debit-notes/{id}/print", captureIdFrom: "/api/debit-notes",
    captureTenant: "trader", segment: "Purchases", tags: ["purchases"],
    explanation: "Printable debit note for the vendor file." }),
  row({ id: "form-pr-detail", kind: "form", title: "Payment received detail", href: "/payments-received",
    capturePath: "/payments-received/{id}", captureIdFrom: "/api/payments-received",
    captureTenant: "services", segment: "Sales", tags: ["sales", "banking", "gl"],
    explanation: "Receipt voucher with allocations to invoices. Print uses the RV template." }),
  row({ id: "form-pr-print", kind: "form", title: "Payment received print", href: "/payments-received",
    capturePath: "/payments-received/{id}/print", captureIdFrom: "/api/payments-received",
    captureTenant: "services", segment: "Sales", tags: ["sales", "banking"],
    explanation: "RV (receipt voucher) print for CR/BR-style collections posted from the payments-received form." }),
  row({ id: "form-bp-detail", kind: "form", title: "Bill payment detail", href: "/bill-payments",
    capturePath: "/bill-payments/{id}", captureIdFrom: "/api/bill-payments",
    captureTenant: "services", segment: "Purchases", tags: ["purchases", "banking", "gl"],
    explanation: "AP payment with bill allocations and optional WHT. Linked GL voucher is CP/BP." }),
  row({ id: "form-bp-print", kind: "form", title: "Bill payment print", href: "/bill-payments",
    capturePath: "/bill-payments/{id}/print", captureIdFrom: "/api/bill-payments",
    captureTenant: "services", segment: "Purchases", tags: ["purchases", "banking"],
    explanation: "PV (payment voucher) print for bill payments." }),
  row({ id: "form-journal-detail", kind: "form", title: "Journal voucher detail", href: "/journal",
    capturePath: "/journal/{id}", captureIdFrom: "/api/reports/journal?start=2020-01-01&end=2030-12-31&limit=1",
    captureIdField: "transaction_id",
    captureTenant: "services", segment: "Accounting", tags: ["ledger", "gl"],
    explanation: "Posted voucher with Dr/Cr lines. Reverse posts an equal-and-opposite JV dated today and unwinds derived invoice/stock state." }),
  row({ id: "form-journal-print", kind: "form", title: "Journal voucher print", href: "/journal",
    capturePath: "/journal/{id}/print", captureIdFrom: "/api/reports/journal?start=2020-01-01&end=2030-12-31&limit=1",
    captureIdField: "transaction_id",
    captureTenant: "services", segment: "Accounting", tags: ["ledger"],
    explanation: "JV / PV / RV print template selected from the voucher prefix (CP/BP → PV, CR/BR → RV, else JV)." }),
  row({ id: "form-customer-detail", kind: "form", title: "Customer record", href: "/customers",
    capturePath: "/customers/{id}", captureIdFrom: "/api/customers",
    captureTenant: "services", segment: "Sales", tags: ["sales"],
    explanation: "Customer card: contacts, terms, opening, Studio fields, and shortcuts into statement, ledger, and customer products." }),
  row({ id: "form-customer-edit", kind: "form", title: "Edit customer", href: "/customers",
    capturePath: "/customers/{id}/edit", captureIdFrom: "/api/customers",
    captureTenant: "services", segment: "Sales", tags: ["sales"],
    explanation: "Customer edit including Studio schema. Deactivate instead of delete when invoices exist." }),
  row({ id: "form-customer-statement", kind: "form", title: "Customer statement", href: "/customers",
    capturePath: "/customers/{id}/statement", captureIdFrom: "/api/customers",
    captureTenant: "services", segment: "Sales", tags: ["sales", "reports", "ledger"],
    explanation: "Opening (pre-period), period invoices with outstanding, receipts, closing. customer_ledger right layers on the customers gate." }),
  row({ id: "form-customer-ledger", kind: "form", title: "Customer ledger", href: "/customers",
    capturePath: "/customers/{id}/ledger", captureIdFrom: "/api/customers",
    captureTenant: "services", segment: "Sales", tags: ["sales", "reports", "ledger"],
    explanation: "AR sub-ledger for one customer — every invoice, credit note, and receipt line in date order." }),
  row({ id: "form-customer-products", kind: "subform", title: "Customer products", href: "/customers",
    capturePath: "/customers/{id}/products", captureIdFrom: "/api/customers",
    captureTenant: "services", segment: "Sales", tags: ["sales", "inventory"],
    explanation: "Items this customer buys (rate plans / SSP). Used by invoicing shortcuts and IFRS 15 allocation when SSP differs per customer." }),
  row({ id: "form-vendor-detail", kind: "form", title: "Vendor record", href: "/vendors",
    capturePath: "/vendors/{id}", captureIdFrom: "/api/vendors",
    captureTenant: "services", segment: "Purchases", tags: ["purchases"],
    explanation: "Vendor card with WHT flags, terms, and shortcuts into AP statement and ledger." }),
  row({ id: "form-vendor-edit", kind: "form", title: "Edit vendor", href: "/vendors",
    capturePath: "/vendors/{id}/edit", captureIdFrom: "/api/vendors",
    captureTenant: "services", segment: "Purchases", tags: ["purchases"],
    explanation: "Vendor edit including Studio schema and withholding tax flags." }),
  row({ id: "form-vendor-statement", kind: "form", title: "Vendor statement", href: "/vendors",
    capturePath: "/vendors/{id}/statement", captureIdFrom: "/api/vendors",
    captureTenant: "services", segment: "Purchases", tags: ["purchases", "reports", "ledger"],
    explanation: "AP statement: opening, period bills, payments, closing. vendor_ledger right layers on the vendors gate." }),
  row({ id: "form-vendor-ledger", kind: "form", title: "Vendor ledger", href: "/vendors",
    capturePath: "/vendors/{id}/ledger", captureIdFrom: "/api/vendors",
    captureTenant: "services", segment: "Purchases", tags: ["purchases", "reports", "ledger"],
    explanation: "AP sub-ledger for one vendor — bills, debit notes, and payments." }),
  row({ id: "form-product-detail", kind: "form", title: "Product record", href: "/products",
    capturePath: "/products/{id}", captureIdFrom: "/api/products",
    captureTenant: "trader", segment: "Inventory", modules: ["inventory"],
    tenants: ["trader", "manufacturing", "hospital", "telecom", "spinning", "processing"],
    tags: ["inventory"],
    explanation: "Product card: type, stock qty, valuation, deferred flag, category, Studio fields, and a link to the stock card." }),
  row({ id: "form-product-edit", kind: "form", title: "Edit product", href: "/products",
    capturePath: "/products/{id}/edit", captureIdFrom: "/api/products",
    captureTenant: "trader", segment: "Inventory", modules: ["inventory"],
    tenants: ["trader", "manufacturing", "hospital", "telecom", "spinning", "processing"],
    tags: ["inventory"],
    explanation: "Product edit. Changing is_deferred affects new invoices only — posted schedules stay." }),
  row({ id: "form-product-stock-card", kind: "subform", title: "Product stock card", href: "/products",
    capturePath: "/products/{id}/stock-card", captureIdFrom: "/api/products",
    captureTenant: "trader", segment: "Inventory", modules: ["inventory"],
    tenants: ["trader", "manufacturing", "hospital", "telecom", "spinning", "processing"],
    tags: ["inventory", "reports"],
    explanation: "Per-item stock card (movements + running qty). Companion to Product Ledger which is the cross-product register." }),
  row({ id: "form-employee-edit", kind: "form", title: "Edit employee · salary structure", href: "/employees",
    capturePath: "/employees/{id}/edit", captureIdFrom: "/api/employees",
    captureTenant: "hospital", segment: "Payroll", modules: ["hrm"], tenants: ["hospital"], tags: ["payroll"],
    explanation: "Employee edit plus the Salary Structure tab (replace-all components from the catalog). Feeds the next payroll run." }),
  row({ id: "form-payroll-detail", kind: "form", title: "Payroll run detail", href: "/payroll",
    capturePath: "/payroll/{id}", captureIdFrom: "/api/payroll/runs",
    captureTenant: "hospital", segment: "Payroll", modules: ["hrm"], tenants: ["hospital"], tags: ["payroll", "gl"],
    explanation: "Run lines, approve, post GL, void. Payslip per employee. Voiding reverses the PR voucher." }),
  row({ id: "form-payslip", kind: "form", title: "Payslip", href: "/payroll",
    capturePath: "/payroll/{id}/payslip/{eid}", captureIdFrom: "/api/payroll/runs", captureIdFrom2: "/api/employees",
    captureTenant: "hospital", segment: "Payroll", modules: ["hrm"], tenants: ["hospital"], tags: ["payroll"],
    explanation: "Printable payslip for one employee on a posted (or draft) run — earnings, deductions, net, bank details." }),
  row({ id: "form-asset-detail", kind: "form", title: "Fixed asset detail", href: "/assets",
    capturePath: "/assets/{id}", captureIdFrom: "/api/assets",
    captureTenant: "services", segment: "Reports", tags: ["assets", "gl"],
    explanation: "Asset card: cost, accum dep, NBV, components (parent_id), impairment, disposal. Depreciation posts through posting.py." }),
  row({ id: "form-lease-detail", kind: "form", title: "Lease contract detail", href: "/leases",
    capturePath: "/leases/{id}", captureIdFrom: "/api/leases",
    captureTenant: "services", segment: "Reports", tags: ["leases", "ifrs", "gl"],
    explanation: "IFRS 16 contract with RoU + liability schedule lines. Hidden when leases_enabled is false." }),
  row({ id: "form-aa-detail", kind: "form", title: "Analytic dimension detail", href: "/analytic-accounts",
    capturePath: "/analytic-accounts/{id}", captureIdFrom: "/api/analytic-accounts",
    captureTenant: "services", segment: "Accounting", tags: ["ledger"],
    explanation: "One analytic dimension (of ≤3). Mark required and journal lines must carry it. Dimensional P&L slices here." }),
  row({ id: "form-bank-import-detail", kind: "form", title: "Bank import detail", href: "/bank-imports",
    capturePath: "/bank-imports/{id}", captureIdFrom: "/api/bank-imports",
    captureTenant: "services", segment: "Banking", tags: ["banking"],
    explanation: "Statement lines + match UI. Unmatched lines stay until you match or exclude; they never auto-post." }),
  row({ id: "form-demand-detail", kind: "form", title: "Purchase demand detail", href: "/purchases/demands",
    capturePath: "/purchases/demands/{id}", captureIdFrom: "/api/purchase-demands",
    captureTenant: "manufacturing", segment: "Purchases", modules: ["purchase_store"], tenants: MILL, tags: ["purchases"],
    explanation: "Demand header + qty lines, approve/cancel/close. Creator cannot approve. Quotations and the comparative hang off this id." }),
  row({ id: "form-demand-edit", kind: "form", title: "Edit purchase demand", href: "/purchases/demands",
    capturePath: "/purchases/demands/{id}/edit", captureIdFrom: "/api/purchase-demands",
    captureTenant: "manufacturing", segment: "Purchases", modules: ["purchase_store"], tenants: MILL, tags: ["purchases"],
    explanation: "Edit is open while the demand is not approved. Qty-only — rates live on quotations." }),
  row({ id: "form-cs-detail", kind: "form", title: "Comparative statement detail", href: "/purchases/comparatives",
    capturePath: "/purchases/comparatives/{id}", captureIdFrom: "/api/comparatives",
    captureTenant: "manufacturing", segment: "Purchases", modules: ["purchase_store"], tenants: MILL, tags: ["purchases"],
    explanation: "Vendor matrix, selected quotation, justification when not lowest, convert-to-PO. One CS per demand (unique)." }),
  row({ id: "form-gi-detail", kind: "form", title: "Gate inward detail", href: "/purchases/gate-inward",
    capturePath: "/purchases/gate-inward/{id}", captureIdFrom: "/api/gate-inwards",
    captureTenant: "manufacturing", segment: "Purchases", modules: ["purchase_store"], tenants: MILL, tags: ["purchases", "inventory"],
    explanation: "GI lines vs PO remaining, vehicle/challan. Cancel-with-reason only while the PO is unbilled. Append-only once billed." }),
  row({ id: "form-go-detail", kind: "form", title: "Gate outward detail", href: "/store/gate-outward",
    capturePath: "/store/gate-outward/{id}", captureIdFrom: "/api/gate-outwards",
    captureTenant: "manufacturing", segment: "Store", modules: ["purchase_store"], tenants: MILL, tags: ["inventory"],
    explanation: "Outward ticket against invoice, debit note, or scrap. Scrap GL posts only at approval." }),
  row({ id: "form-si-detail", kind: "form", title: "Store issue detail", href: "/store/issues",
    capturePath: "/store/issues/{id}", captureIdFrom: "/api/store-issues",
    captureTenant: "manufacturing", segment: "Store", modules: ["purchase_store"], tenants: MILL, tags: ["inventory", "gl"],
    explanation: "Posted issue: expense account, analytic tag, lines, and the stock/GL voucher created on save." }),
  row({ id: "form-po-detail", kind: "form", title: "Purchase order detail", href: "/manufacturing/purchase-orders",
    capturePath: "/manufacturing/purchase-orders/{id}", captureIdFrom: "/api/purchase-orders",
    captureTenant: "manufacturing", segment: "Purchases", modules: ["purchase_store"], tenants: MILL, tags: ["purchases"],
    explanation: "PO with demand/comparative FKs, remaining qty vs GI, convert-to-bill when coverage rules pass." }),
  row({ id: "form-po-print", kind: "form", title: "Purchase order print", href: "/manufacturing/purchase-orders",
    capturePath: "/manufacturing/purchase-orders/{id}/print", captureIdFrom: "/api/purchase-orders",
    captureTenant: "manufacturing", segment: "Purchases", modules: ["purchase_store"], tenants: MILL, tags: ["purchases"],
    explanation: "Printable PO for the vendor. Rates are hidden from gate-only users on the live GI flow, not on this print." }),
  row({ id: "form-grn-detail", kind: "form", title: "GRN detail", href: "/manufacturing/grn",
    capturePath: "/manufacturing/grn/{id}", captureIdFrom: "/api/grn",
    captureTenant: "manufacturing", segment: "Manufacturing", modules: ["production"], tenants: ["manufacturing"], tags: ["purchases", "inventory"],
    explanation: "Goods receipt against a PO with stock in. Used when the mill is not running gate inward." }),
  row({ id: "form-grn-print", kind: "form", title: "GRN print", href: "/manufacturing/grn",
    capturePath: "/manufacturing/grn/{id}/print", captureIdFrom: "/api/grn",
    captureTenant: "manufacturing", segment: "Manufacturing", modules: ["production"], tenants: ["manufacturing"], tags: ["purchases"],
    explanation: "Printable goods receipt note for the mill file — qty received against the PO, no rates if the viewer is gate-only." }),
  row({ id: "form-bom-detail", kind: "form", title: "BoM detail", href: "/manufacturing/boms",
    capturePath: "/manufacturing/boms/{id}", captureIdFrom: "/api/bom",
    captureTenant: "manufacturing", segment: "Manufacturing", modules: ["production"], tenants: ["manufacturing"], tags: ["manufacturing"],
    explanation: "Bill of materials: finished item, component list, scrap expectations." }),
  row({ id: "form-mo-detail", kind: "form", title: "Production order detail", href: "/manufacturing/production-orders",
    capturePath: "/manufacturing/production-orders/{id}", captureIdFrom: "/api/production-orders",
    captureTenant: "manufacturing", segment: "Manufacturing", modules: ["production"], tenants: ["manufacturing"], tags: ["manufacturing", "gl"],
    explanation: "Issue, complete, scrap on a work order. WIP/FG postings go through posting.py." }),
  row({ id: "form-mo-print", kind: "form", title: "Production order print", href: "/manufacturing/production-orders",
    capturePath: "/manufacturing/production-orders/{id}/print", captureIdFrom: "/api/production-orders",
    captureTenant: "manufacturing", segment: "Manufacturing", modules: ["production"], tenants: ["manufacturing"], tags: ["manufacturing"],
    explanation: "Shop-floor print of the work order and components to issue." }),
  row({ id: "form-xfer-detail", kind: "form", title: "Warehouse transfer detail", href: "/inventory/transfers",
    capturePath: "/inventory/transfers/{id}", captureIdFrom: "/api/stock-transfers",
    captureTenant: "trader", segment: "Inventory", modules: ["inventory"],
    tenants: ["trader", "manufacturing", "hospital", "telecom", "spinning", "processing"],
    tags: ["inventory"],
    explanation: "Ship / receive a transfer. Status draft → shipped → received." }),
  row({ id: "form-patient-detail", kind: "form", title: "Patient record", href: "/healthcare/patients",
    capturePath: "/healthcare/patients/{id}", captureIdFrom: "/api/healthcare/patients",
    captureTenant: "hospital", segment: "Healthcare", modules: ["healthcare"], tenants: ["hospital"], tags: ["healthcare", "sales"],
    explanation: "Patient (MR-YYYYNNNN) with auto-linked Customer, visits, admissions, and lab orders." }),
  row({ id: "form-ipd-detail", kind: "form", title: "Admission detail", href: "/healthcare/ipd",
    capturePath: "/healthcare/ipd/{id}", captureIdFrom: "/api/healthcare/admissions",
    captureTenant: "hospital", segment: "Healthcare", modules: ["healthcare"], tenants: ["hospital"], tags: ["healthcare", "sales"],
    explanation: "IPD admission: bed, deposit, charge accumulator, discharge to a consolidated invoice. Charges have no per-line GL until discharge." }),
  row({ id: "form-lab-detail", kind: "form", title: "Lab order detail", href: "/healthcare/lab",
    capturePath: "/healthcare/lab/{id}", captureIdFrom: "/api/healthcare/lab/orders",
    captureTenant: "hospital", segment: "Healthcare", modules: ["healthcare"], tenants: ["hospital"], tags: ["healthcare"],
    explanation: "Lab order: collect sample, enter results (unit/range from catalogue), deliver." }),
  row({ id: "form-spin-lot-detail", kind: "form", title: "Spin lot detail", href: "/spinning/lots",
    capturePath: "/spinning/lots/{id}", captureIdFrom: "/api/spinning/lots",
    captureTenant: "spinning", segment: "Spinning", modules: ["spinning"], tenants: ["spinning"], tags: ["spinning", "gl"],
    explanation: "Lot control record: recipe, stages, cone output, waste, GL through spinning_posting. RM 1200 → WIP 1201–1203 → FG 1204." }),
  row({ id: "form-wv-contract-detail", kind: "form", title: "Weaving contract detail", href: "/weaving/contracts",
    capturePath: "/weaving/contracts/{id}", captureIdFrom: "/api/weaving/contracts",
    captureTenant: "manufacturing", segment: "Weaving", modules: ["weaving"], tenants: ["manufacturing"], tags: ["weaving"],
    explanation: "Contract with rates, yarn inward, sizing, production, and dispatch progress. Memo/ops — no GL in v1." }),
  row({ id: "form-wb-ticket-detail", kind: "form", title: "Weighbridge ticket detail", href: "/weighbridge/tickets",
    capturePath: "/weighbridge/tickets/{id}", captureIdFrom: "/api/weighbridge/tickets",
    captureTenant: "manufacturing", segment: "Weighbridge", modules: ["weighbridge"], tenants: WB, tags: ["weighbridge"],
    explanation: "Two-weigh ticket: first/second weigh, net kg, optional copy of gate pass onto a linked invoice’s Studio field." }),
  row({ id: "form-tp-lot-detail", kind: "form", title: "Processing lot detail", href: "/processing/lots",
    capturePath: "/processing/lots/{id}", captureIdFrom: "/api/textile-processing/lots",
    captureTenant: "processing", segment: "Processing", modules: ["textile_processing"], tenants: ["processing"], tags: ["processing"],
    explanation: "Grey lot timeline: mending, kachi/pakki parchi, PPC stages, inspection, dispatch, settlement." }),
  row({ id: "form-kachi-detail", kind: "form", title: "Kachi parchi detail", href: "/processing/kachi-parchi",
    capturePath: "/processing/kachi-parchi/{id}", captureIdFrom: "/api/textile-processing/kachi-parchis",
    captureTenant: "processing", segment: "Processing", modules: ["textile_processing"], tenants: ["processing"], tags: ["processing"],
    explanation: "Rough process ticket against a grey lot — the mill’s in-process voucher before pack." }),
  row({ id: "form-pakki-detail", kind: "form", title: "Pakki parchi detail", href: "/processing/pakki-parchi",
    capturePath: "/processing/pakki-parchi/{id}", captureIdFrom: "/api/textile-processing/pakki-parchis",
    captureTenant: "processing", segment: "Processing", modules: ["textile_processing"], tenants: ["processing"], tags: ["processing"],
    explanation: "Packed ticket before fresh dispatch. Closes the process loop on the lot." }),
  row({ id: "form-ogp-detail", kind: "form", title: "Rejection OGP detail", href: "/processing/rejection",
    capturePath: "/processing/rejection/ogp/{id}", captureIdFrom: "/api/textile-processing/rejection-ogps",
    captureTenant: "processing", segment: "Processing", modules: ["textile_processing"], tenants: ["processing"], tags: ["processing"],
    explanation: "Outward gate pass for rejected grey returning to the customer — custody relief, not a sales invoice." }),
  row({ id: "form-consol-run", kind: "form", title: "Consolidation run detail", href: "/consolidation",
    capturePath: "/consolidation/runs/{id}", captureIdFrom: "/api/consolidation/runs",
    captureTenant: "services", segment: "Reports", tags: ["reports", "ifrs"],
    explanation: "IFRS 10 worksheet: members, eliminations, statements. Eliminations never post to member GLs — they live on the holding run only." }),
]

const SUB_REPORTS: CatalogEntry[] = [
  row({ id: "report-hc-opd", kind: "report", title: "Healthcare · OPD summary", href: "/healthcare/reports?tab=opd",
    capturePath: "/healthcare/reports?tab=opd", captureTenant: "hospital", segment: "Healthcare",
    modules: ["healthcare"], tenants: ["hospital"], tags: ["healthcare", "reports"],
    explanation: "OPD visits and collections for the date range. One of seven HC reports; revenue accounts 4100–4121." }),
  row({ id: "report-hc-doctors", kind: "report", title: "Healthcare · Doctor collections", href: "/healthcare/reports?tab=doctors",
    capturePath: "/healthcare/reports?tab=doctors", captureTenant: "hospital", segment: "Healthcare",
    modules: ["healthcare"], tenants: ["hospital"], tags: ["healthcare", "reports"],
    explanation: "Collections by doctor — the same figures the AI healthcare agent can quote." }),
  row({ id: "report-hc-lab", kind: "report", title: "Healthcare · Lab summary", href: "/healthcare/reports?tab=lab",
    capturePath: "/healthcare/reports?tab=lab", captureTenant: "hospital", segment: "Healthcare",
    modules: ["healthcare"], tenants: ["hospital"], tags: ["healthcare", "reports"],
    explanation: "Lab orders collected, resulted, delivered — volume not GL (billing follows visit/admission)." }),
  row({ id: "report-hc-ipd", kind: "report", title: "Healthcare · IPD census", href: "/healthcare/reports?tab=ipd",
    capturePath: "/healthcare/reports?tab=ipd", captureTenant: "hospital", segment: "Healthcare",
    modules: ["healthcare"], tenants: ["hospital"], tags: ["healthcare", "reports"],
    explanation: "Bed occupancy and admissions in the window. Discharge invoices land on the revenue-by-type tab." }),
  row({ id: "report-hc-revenue", kind: "report", title: "Healthcare · Revenue by type", href: "/healthcare/reports?tab=revenue",
    capturePath: "/healthcare/reports?tab=revenue", captureTenant: "hospital", segment: "Healthcare",
    modules: ["healthcare"], tenants: ["hospital"], tags: ["healthcare", "reports", "gl"],
    explanation: "GL 4100–4121 service revenue split (consult, lab, procedure, IPD). This is books, not the memo charge accumulator." }),
  row({ id: "report-forecast-revenue", kind: "report", title: "Forecast · Revenue", href: "/agent/forecast?tab=revenue",
    capturePath: "/agent/forecast?tab=revenue", captureTenant: "services", segment: "System",
    modules: ["ai_assistant"], tenants: ALL, tags: ["ai", "reports"],
    explanation: "Agent forecast of revenue from posted invoices. Requires the AI assistant module; this is analytics, not a GL budget." }),
  row({ id: "report-forecast-cash", kind: "report", title: "Forecast · Cash flow", href: "/agent/forecast?tab=cash",
    capturePath: "/agent/forecast?tab=cash", captureTenant: "services", segment: "System",
    modules: ["ai_assistant"], tenants: ALL, tags: ["ai", "reports", "banking"],
    explanation: "Forward cash view from open AR/AP and bank books. Companion to the statutory cash-flow statement." }),
  row({ id: "report-forecast-risk", kind: "report", title: "Forecast · Customer risk", href: "/agent/forecast?tab=risk",
    capturePath: "/agent/forecast?tab=risk", captureTenant: "services", segment: "System",
    modules: ["ai_assistant"], tenants: ALL, tags: ["ai", "reports", "sales"],
    explanation: "Overdue concentration and customer risk scores derived from AR aging." }),
  row({ id: "report-forecast-budget", kind: "report", title: "Forecast · Budget variance", href: "/agent/forecast?tab=budget",
    capturePath: "/agent/forecast?tab=budget", captureTenant: "services", segment: "System",
    modules: ["ai_assistant"], tenants: ALL, tags: ["ai", "reports"],
    explanation: "Budget vs actual variance the agent uses when answering month-end questions." }),
  row({ id: "report-attendance", kind: "report", title: "Attendance report", href: "/attendance/report",
    captureTenant: "hospital", segment: "Payroll", modules: ["hrm"], tenants: ["hospital"], tags: ["payroll", "reports"],
    explanation: "Monthly attendance export/print. Biometric rows cannot be deleted from the grid; this report still includes them." }),
  row({ id: "report-custody", kind: "report", title: "Custody stock", href: "/manufacturing/stock-locations/custody",
    captureTenant: "manufacturing", segment: "Manufacturing", modules: ["production"], tenants: ["manufacturing"],
    tags: ["manufacturing", "inventory", "reports"],
    explanation: "Customer-owned stock sitting in mill locations (lot + qty). Textile processing grey is the same idea on a different module." }),
  row({ id: "report-movements", kind: "report", title: "Location movements", href: "/manufacturing/stock-locations/movements",
    captureTenant: "manufacturing", segment: "Manufacturing", modules: ["production"], tenants: ["manufacturing"],
    tags: ["manufacturing", "inventory", "reports"],
    explanation: "Warehouse movement register by location — issues, receipts, transfers." }),
]

const EXTRA_SCREENS: CatalogEntry[] = [
  row({ id: "screen-alerts", kind: "screen", title: "Alerts", href: "/alerts",
    captureTenant: "services", segment: "System", tags: ["settings", "approvals", "sales"],
    explanation: "In-app inbox: overdue invoices, low stock, approvals waiting, disputes. Distinct from email overdue reminders (Settings → notifications)." }),
  row({ id: "screen-forecast", kind: "screen", title: "Forecasts", href: "/agent/forecast",
    captureTenant: "services", segment: "System", modules: ["ai_assistant"], tenants: ALL, tags: ["ai", "reports"],
    explanation: "Four forecast panes (revenue, cash, customer risk, budget variance) fed by /api/agent. Install AI Assistant from Add-ons." }),
  row({ id: "screen-attendance-bulk", kind: "subform", title: "Attendance bulk entry", href: "/attendance/bulk",
    captureTenant: "hospital", segment: "Payroll", modules: ["hrm"], tenants: ["hospital"], tags: ["payroll"],
    explanation: "Grid upsert of a day’s attendance for many employees. Hours compute from time-in/time-out; status present/absent/half_day/leave." }),
  row({ id: "screen-attendance-import", kind: "subform", title: "Biometric attendance import", href: "/attendance/import",
    captureTenant: "hospital", segment: "Payroll", modules: ["hrm"], tenants: ["hospital"], tags: ["payroll"],
    explanation: "CSV/device import matched by employee_code, source=biometric, raw_data stored. Those rows cannot be deleted." }),
  row({ id: "screen-attendance-record", kind: "form", title: "Attendance record", href: "/attendance/record",
    captureTenant: "hospital", segment: "Payroll", modules: ["hrm"], tenants: ["hospital"], tags: ["payroll"],
    explanation: "Single punch: employee, date, time in/out, status. Manual source — distinct from biometric import." }),
  row({ id: "screen-settings-billing", kind: "screen", title: "Settings · Billing", href: "/settings/billing",
    captureTenant: "services", segment: "System", tags: ["settings"],
    explanation: "SaaS plan and Stripe billing for the tenant. Demo companies show the catalog of plans; production uses STRIPE keys." }),
  row({ id: "screen-settings-ops", kind: "screen", title: "Settings · Ops console", href: "/settings/ops",
    captureTenant: "services", segment: "System", tags: ["settings"],
    explanation: "Operator console for practice/host staff: tenant list, health, dead-letter tasks. Not the company Settings form." }),
  row({ id: "screen-settings-webhooks", kind: "screen", title: "Settings · Webhooks", href: "/settings/webhooks",
    captureTenant: "services", segment: "System", tags: ["settings"],
    explanation: "Outbound webhook endpoints for invoice/payment events. Secrets are write-only; deliveries retry from the task queue." }),
]

export const DEEP_ENTRIES: CatalogEntry[] = [
  ...STUDIO,
  ...FORMS,
  ...DETAILS,
  ...SUB_REPORTS,
  ...EXTRA_SCREENS,
]
